### ISSUE TITLE
Increase the property value size

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#468]
We are using Cerberus to test our Web Services and we are using property composition to construct requests. However, there is a restriction on the property value size, which can't currently exceed 2500 characters.

This restriction causes a serious limitation to the request construction. Indeed, we can't test Web Services with more than 2500 characters in their request. Note that we wouldn't directly use the SoapLibrary to register our hard coded requests. We would rather register a 'parameterized' form of our requests and be able to tune them inside the Test Case.

Could we be able to handle more than 2500 characters for a property value (value1 or value2)? I know this change can seriously increase the database space so we have to think about a smart solution. Maybe by using several tables according to the property type and only increase property value size for text properties?

**Comment by vertigo17** [comment]
Size is already at 3000 which is quite big.
I checked at some examples when we reached that hight values and it is only when we store complete HTML javascript code or even binary objects. That is not a correct usage...
For the time being there are no specific real cases to have those field bigger.
Once we have a real need, we may enlarge it.
NB : target for the execution is to denormalise all testcase data into the execution in order to secure any modification on the test case definition do not 'change' any execution. 1 execution is done once for all and should never be modified.
