### ISSUE TITLE
Clean security-constraint in the web.xml 

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#505]
Some servlet are not allowed in the right group.

**Comment by vertigo17** [comment]
I created a quick script in order to check that for every servlet we have 2 lines on the web.xml file.
That will allow us to identify easilly the servlet that have either no access defined (1 in th list) and the one that belong to more than 1 security-constraint (>=3 in the list).
I will try to clean those ones and proceed with the jsp.

GetTestDataLibData.java 3
GetTestDataLib.java 3
FindExecutionInQueue.java 1
DeleteExecutionInQueue.java 1
UpdateExecutionInQueue.java 1
SavePicture.java 0
GetCountryForTestCase.java 3
ExportTestCase.java 1
UpdateTestCaseField.java 1
GetStepInLibrary.java 1
ImportTestCaseFromJson.java 1
GetPropertiesForTestCase.java 1
CampaignExecutionRadarGraphByFunction.java 1
CreateSoapLibrary.java 1
DeleteSoapLibrary.java 1
FindAllSoapLibrary.java 1
UpdateSoapLibrary.java 1
Thumbnailer.java 0
FindTestImplementationStatusPerApplication.java 1
VirtualProxy.java 0
FindEnvironments.java 0
GetEnvironmentAvailable.java 3
AddToExecutionQueue.java 1
ExecuteNextInQueue.java 1
UpdateCountryEnvironmentDatabase.java 1
DeleteCountryEnvironmentDatabase.java 1
CreateCountryEnvironmentDatabase.java 1
FindCountryEnvironmentDatabase.java 1
GetReport.java 1
GeneratePerformanceString.java 0
SaveManualExecutionPictureTest.java 0
GetReportTest.java 0

**Comment by vertigo17** [comment]
web.xml file is now cleaned and script is in place to control it stays clean.
I close the ticket.
