### ISSUE TITLE
Run Multiple Tests > Manual Execution and Run the Test Case again

### ISSUE THREAD

**Issue by BenjaminFr** [vertigo17/Cerberus#516]
After executing a test case in the context of a manual execution with a tag

If for example, I define my test case KO and I would replay the still manually on the same tag, same environnement, same country...

I click on the run number, then click "Run the same Test Case again." (See attachment ![08](https://cloud.githubusercontent.com/assets/11309774/6579243/548d1bca-c749-11e4-9d37-740447890874.jpg)

Here, we can ensure that I am redirected to the page execution with all my initial execution parameters identical please (Tag, environnement, country...) ? (See attachment ![10](https://cloud.githubusercontent.com/assets/11309774/6579282/96bc0bb4-c749-11e4-88b1-c2a2dc765b6d.jpg)

Thanks

**Comment by bcivel** [comment]
Development done as expected.
@BenjaminFr Could you validate and close issue?

**Comment by BenjaminFr** [comment]
If i click on "Run the same Test Again", i would like to go directly on the test execution.

**Comment by BenjaminFr** [comment]
@bcivel I still have the old behavior . Can you check please ?

**Comment by afnogueira** [comment]
@BenjaminFr  In order to reproduce this bug, can you please send me the link for the execution detail page for which you want to click "Run the same test case again"?

**Comment by BenjaminFr** [comment]
This is the link that is present on my first screenshot

**Comment by afnogueira** [comment]
@BenjaminFr  In order to address this issue, the solution that I propose is to have two hyperlinks (check pictures attached):
* (1) Run the same Test Case again
* (2) Edit configurations and Run the same Test Case again 

If you have access to the Cerberus QA environment, you can check the proposed solution - click [here] (http://192.168.134.197/CerberusQA/ExecutionDetail.jsp?id_tc=20217258)


![manualexecution_link](https://cloud.githubusercontent.com/assets/11045914/7475150/c1fff2de-f33d-11e4-8614-d2004be16db5.png)

**(1) The first link opens the page that allows the manual execution process - the exact same configurations are used to run the test case.**

![manual_executionpage](https://cloud.githubusercontent.com/assets/11045914/7475629/a7f12dec-f340-11e4-83c5-cfe041c84130.png)

**(2) The second link opens the page that allows the user to configure and run a test case  - the user is able to change configurations (e.g, tag, country,...)** 

![runtestspage](https://cloud.githubusercontent.com/assets/11045914/7475674/e0c327ec-f340-11e4-8af5-8dc973d8f805.png)

**Comment by BenjaminFr** [comment]
@afnogueira I did some tests and compare with today existing . Evolution is adapted . Thank you

**Comment by bcivel** [comment]
Works
