### ISSUE TITLE
Filter selection doesn't work on reportingByTag page

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#528]
ShortDescription,Start,Comment,Status,Application,BugID,ControlMessage

**Comment by afnogueira** [comment]
I was testing the page ReportingExecutionByTag.jsp in order to reproduce this bug, and I notice that Firebug is raising some errors while the page is loading:
* Chart.js:
** Problem: sometimes the radius is < 0  (this.outerRadius and this.innerRadius sometimes have negative values)
** where: line 1181 and line 1183

* campaignReport.js:
** Problem: sometimes the $(element).get(0) does not exist
** where: line 504

**Comment by afnogueira** [comment]
I think that the bug can be solved by adding something like the code above in the:
File: campaignReport.js
Function: showOrHideColumns() 

```
//search for all elements with the class columnName <div class="columName"> that are inside the divs TableLine > TestPart
//For instance, for the column "ShortDescription", it will search for all elements that match the following: 
//<div class="TableLine"><div class="TestPart"><div class="ShortDescription"></div></div></div>

var criteria = "div.TableLine > .TestPart > ." + columnName;

// if there are elements that match the column associated with the checkbox, then we can hide/show them
if($(document).find(criteria).length !== 0){         
	if(checkboxElem.checked){
		$(document).find(criteria).show();    
	}else{    
		$(document).find(criteria).hide();
	}
}   
```

**Comment by afnogueira** [comment]
@bcivel please confirm if the bug is fixed.

**Comment by bcivel** [comment]
This is OK for ShortDescription,Comment,Status,Application,BugID,
Not OK for ControlMessage and Start.

**Comment by afnogueira** [comment]
@bcivel you can now check if it is working for the ControlMessage and Start fields

**Comment by bcivel** [comment]
It works
Thanks
