### ISSUE TITLE
 Report columns does adpate more width

### ISSUE THREAD

**Issue by BenjaminFr** [vertigo17/Cerberus#537]
On execution by Tag report

See for example : "UAT_preview_new_pdp"

Select all countries then withdraw

There was a regression = The report columns does adpate more width

Can we adapt to the number of selected countries please ?

**Comment by BenjaminFr** [comment]
See #520 : There has been a regression on these points. Can we replace them ?

**Comment by afnogueira** [comment]
@BenjaminFr I have committed the fix for the regression associated with the issue #520 (introduced by last modifications). You can check it now in the QA environment (*.197) or you can check it after the new version of Cerberus is deployed to the server (*.55).

**Comment by BenjaminFr** [comment]
Problem is always present. Can you check please ?

**Comment by afnogueira** [comment]
@BenjaminFr  Yes, I will check. Can you please post a picture with the problem? (just to check that I am really understanding the issue). Thank you.

**Comment by BenjaminFr** [comment]
![1](https://cloud.githubusercontent.com/assets/11309774/7469039/76985ada-f30f-11e4-91c8-c763a11a098e.png)

See attachment. Thanks

**Comment by afnogueira** [comment]
@BenjaminFr  Do you have access to the Cerberus QA environment? If yes, click 
[here](http://192.168.134.197/CerberusQA/ReportingExecutionByTag.jsp?Tag=new_PDP) and check if it is working as expected.

The fix is implemented in the QA environment but is not available yet in production. As soon as it available I'll let you know. Thank you.

**Comment by bcivel** [comment]
I confirm fix solve this issue.
