### ISSUE TITLE
Cerberus tries to calculate properties when it encounters special characters between percentages

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#539]
This issue happens when implicitly calculating a property in a control. Cerberus tries to recalculate all the dependent properties and fails to do it when property is defined with something like this:

SELECT * FROM table where value = %*%   

OR

SELECT * FROM table where value = %+%

Examples of failed executions:

/Cerberus/ExecutionDetail.jsp?id_tc=20287476
/Cerberus/ExecutionDetail.jsp?id_tc=20287763

**Comment by afnogueira** [comment]
The expressions ```%*%``` and ```%+%``` were being identified as properties by Cerberus. The problem is that these are part of a SQL query and therefore, they should not be replaced with any value (i.e., these are not properties). The committed solution defines a restriction for **executeSql** and **executeSqlFromLib** properties that will disregard any expression enclosed by  ```%% ``` that is not defined in set of properties for the test case. For instance, if we have the SQL expression:

```select columnA from table where columnB LIKE '%XPTO%' ```

* If property XPTO (with value='hello world') is defined, then the SQL expression will be translated to:
	```select columnA from table where columnB LIKE 'hello world'```
* If the property XPTO is **not** defined, then the SQL expression will be translated to:
	```select columnA from table where columnB LIKE '%XPTO%'```

**Comment by cjmachado** [comment]
Confirmed that the issue is fixed. 
Thanks!
