### ISSUE TITLE
SOAP Library improvements

### ISSUE THREAD

**Issue by cjmachado** [vertigo17/Cerberus#540]
SOAP Library is great to use WebServices to test applications. My proposal is to change how this Library works in order to test WebServices (although possible, the available features are limited).

The changes were already discussed during a meeting with the Cerberus developers.

**Comment by bcivel** [comment]
linked with #264.

**Comment by vertigo17** [comment]
TestDataLib is now fully implemented so I close the issue (althoug TestDataLib should not be used to test Webservice but more to get data to test).
Testgin a SOAP should be done using callSOAP action that save the result in memory so that controls can be made on it (just like it works browsing a web application).
No specific improvements has been identified on callSoap Actions.
