### ISSUE TITLE
Clean the Test Case UI from deprecated fields

### ISSUE THREAD

**Issue by gpelissier** [vertigo17/Cerberus#541]
I've had my first review of Cerberus today.
Seems like a lot of deprecated fields in the test case UI are kept only for the sake of some senior users.

This probably makes things pointlessly harder to understand/use for beginners. 

Could there be an option to hide/show those fields (hidden by default) -> the UI would be cleaner and more user friendly.
I think Benoit Clivez will be more aware of which fields to keep or hide, the two coming to my mind are the fulltext ones (including the "How to").

**Comment by afnogueira** [comment]
@gpelissier @bcivel please provide a list of the fields that are considered deprecated 

Please note that some of these attributes, including the "How to", are important because they aid the ones that have to: i) execute the test cases, ii) observe their behaviour and iii) analyse the test cases' results. Even for automated tests, these descriptions are quite helpful.
