### ISSUE TITLE
Allow to execute SQL Script without any expected result

### ISSUE THREAD

**Issue by bcivel** [vertigo17/Cerberus#594]
The need is to perform SQL to insert/delete and to execute ProcStoc that don't give any return.
Usage on property doesn't fit because it is not an sql to expect to retreive data, but to perform action.

Two approaches:
> Add 1 action (executeSql) and a couple of identifier (updateScript=, insertScript=, deleteScript=, storedProcedure=)
> Add 4 actions : executeSqlUpdate, executeSqlInsert, executeSqlStoredProc.....

I start develop the first proposal as core development is the same. Let's agree on the approach we take.

**Comment by cjmachado** [comment]
In my humble opinion, I really recommend against allowing to execute INSERTs, DELETEs or UPDATEs, specially if we are talking about cases that run in production environments. This feature will allow the user to:
- Corrupt the database;
- Bypass the APIs.

**Comment by gmoita** [comment]
For me it represents a very high risk.
I will consider it only if it will only work outside PROD group. This is, if the sql to perform does not start by SELECT, it will not be able to execute on PROD group.
Rather than that, I completely disagree, by the same reasons as cjmachado.

**Comment by bcivel** [comment]
This kind of security have to be managed at the database level, where it possible to configure it deeply (read/write rights by environment, but also by table). Not sure it necessary to add this kind of security in Cerberus.

If update is not allowed by database right, a FA will be raised with specific error message.

**Comment by afnogueira** [comment]
I share the security concerns with @gmoita and @cjmachado, but if you're confident that the security issues can be addressed through database configurations, I am all for it. I understand how these types of operations seem to be useful to test users, however, I would like to propose analysing things in a different perspective: **the test database consistency**.

Imagine that Cerberus' users have their own database for tests (the QA database), which is a copy of the production database. The QA database is expected to match the business logic, with the purpose of allowing us to test the application features without impacting the production data.

If we allow test users to perform steps in which they can modify (insert/delete/update) the test data disregarding the business logic, what will happen to the QA database?

We should also think about these questions, before proceeding:

- If the test data is not valid according to the business logic, is the effort of testing really worth it?
- What will be the impact for the test cases that are currently working (and well implemented)? Will we have more false positives, i.e., will we have an increased number of failing tests because the test environment is disrupted?
- What will be the effort to restore the database to a valid state? If these types of operations are to be allowed in a test case, then will a rollback be performed after the test case finishes?

**Comment by cjmachado** [comment]
@bcivel Placing the security at the database level is not possible. The database user is the same for all the application users.
Bypassing the APIs is also something that worries me.

**Comment by bcivel** [comment]
Thanks for your feedback. 
@cjmachado Giving the possibility to the community to do something doesn't mean that it must be used in your context. If you only set the read right for the user Cerberus, it won't change anything.
@afnogueira The questions you propose to consider have to be considered before using the functionnality.
I understand in your context it's dangerous to proceed that way but in other context, for example if we want to test a stored procedure, or in case we don't have api available, it could be useful to have it. 

I already made the core development but it is unavailable because I don't add the invariant to propose the action. If we don't want to have it, I'll clean it and proceed another way (building another pluggin doing that stuff and callable by Cerberus using http). If we aggree, I'll complete it adding the invariant and documentation.

**Comment by cjmachado** [comment]
@bcivel It's not just the user cerberus (and you can't grant only the read rights to this user, the application would stop working...), it's all the database users from all the connection pools registered in Cerberus (at least, all AS400 environments). 
If this is something for the community, then I suggest that you implement it in such a way that it's possible for us to completely disable this feature. Having said that, in point my of view, it would be interessing to call stored procedures, but that's as far as I wish you'd go.

**Comment by cjmachado** [comment]
Just to make it clear, when I say cerberus user, I'm also including the user that accesses the Cerberus database, whose connection pool is also created in the application.

**Comment by bcivel** [comment]
@cjmachado You're right for the connection to Cerberus. As it's mandatory to grant all right to that user for Cerberus to work correctly, this is necessary to remove the possibility to run update through this connection pool.

For all other databases (including all your AS400), it's possible to restrict the right as read only. It's even possible to give right at the table level as described here .http://www.go4as400.com/subsystem-jobs-user-profile-in-as400/jobs.aspx?cid=14.

It's the best way for you to restrict the usage of this feature.

**Comment by bcivel** [comment]
Done
