### ISSUE TITLE
Test case without number not editable

### ISSUE THREAD

**Issue by thomas-aw** [vertigo17/Cerberus#616]
When you don't enter a number for a test case and you save it, you cannot edit this test case.

**Comment by afnogueira** [comment]
Related to issue: #575

**Comment by afnogueira** [comment]
@thomas-aw  A test case without its number should not be allowed, because test case number is part of the key that unequivocally identifies a test case. 
Therefore, to avoid future mistakes, I've added client-side validations, according to the following rules:

* test = empty and test case = empty -> updates the current test case
* test = empty and test case != empty -> adds a new test case in the current test
* test != empty and test case = empty -> asks for test case number
* test != empty and test case != empty -> adds the specific test case in the specific test

The server-side validations will also be improved, upon converting the test case page.
