### ISSUE TITLE
application name limitation

### ISSUE THREAD

**Issue by NotoriousBig** [vertigo17/Cerberus#629]
Hi dev Team, 

I'd like to create applications named with more than 45 char 
My application names would be somehting like "RFR_Publication_MediaPublish_001_FROM_MEDIA-STORAGE" as already defined in SVN

Sébastien

**Comment by vertigo17** [comment]
What about putting 200 ?

**Comment by cjmachado** [comment]
+1 for this request. 
I also agree with 200 characters, it should be more than enough for our needs.
SITD is currently opening changes to rename their projects in Jenkins and I must also rename the application name in Cerberus, otherwise we'll break the revision integration. Another example for an application name (49 characters): redoute-globalstock-batch-VCJGlobalStockMovement

**Comment by vertigo17** [comment]
Application can now get to 200 caracters. Please reopen if necessary.
