### ISSUE TITLE
Show information of Maven release on Notification page (newbuildrevision event)

### ISSUE THREAD

**Issue by gmoita** [vertigo17/Cerberus#683]
Cerberus Version : 1.1.4-SNAPSHOT

We would like to have visible, on the Notificatio.jsp page (with newbuildrevision event), near the release number on the "Application to deploy" area, the follwoing information:
- Description of the release line, or
- the Maven Group ID + Maven Artifact ID + Maven Version

When having a lot of releases to deploy, this is very usefull to "control" the correct version and to verify that everything was deployed on the servers, as requested by Cerberus.

**Comment by vertigo17** [comment]
Notification.jsp is no longer maintained and should be replaced by the New Environment screen.
Please have a look at the new screen as it already have the Maven Version displayed.
It does not have the group id or artefact but I can add it easily. Check the new screen and confirm if you still want it.
The description make no reall sense as it correspond to the comment of the last comit. Most of the time it will be a technical standard comment with no usefull information.  

![selection_010](https://cloud.githubusercontent.com/assets/5342048/13731231/6c7b4750-e964-11e5-9a94-94e42ef7189f.jpg)

**Comment by gmoita** [comment]
Maven version is just enough.
However, currenty, information is not visible like you show.
Example below:
![issue 683 - installation instructions not visible](https://cloud.githubusercontent.com/assets/5640464/13741818/2bb3ef8a-e9d0-11e5-90a6-b90d204fa7b2.jpg)

Do you want me to open another issue?

**Comment by vertigo17** [comment]
The rule is that when the link field is not empty, the release is considered as manual and appear in the installation instructions.
It looks in your example that the lines 1, 3 and 5 has been enriched with a link information so the consequence is that it appears in install instructions.
Remove the link (or don't feed it) for all release lines entered directly by Jenkins and it will clean the install instruction only keeping the necessary lines.
This is in fact a loss of time to change those automatic lines that comes directly from the comit.

Anyway, on the example provided I will add a carriage return on link instruction in order to make the screen more usable.

**Comment by vertigo17** [comment]
I removed the possibility to edit the link information in buildcontent page when the release is automatic.
That will prevent this issue to happen in the future.
