### ISSUE TITLE
Many errors during SQL table initialization

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#684]
When I'm trying to initialize database for the first time, I've got many SQL errors:

<img width="1256" alt="capture d ecran 2016-03-11 a 11 50 07" src="https://cloud.githubusercontent.com/assets/1511715/13700222/e06f490e-e77f-11e5-9c4e-ae3488cdee25.png">

<img width="1258" alt="capture d ecran 2016-03-11 a 11 50 48" src="https://cloud.githubusercontent.com/assets/1511715/13700223/e4715fd8-e77f-11e5-97ad-f98a7f668d6c.png">

<img width="1256" alt="capture d ecran 2016-03-11 a 11 59 35" src="https://cloud.githubusercontent.com/assets/1511715/13700351/c7fc28fa-e780-11e5-9f84-300ca095068d.png">

(and so on...)

It may be due to the use of bad timestamp format for default value (0000-00-00 00:00:00) when invalid dates are not allowed (http://dev.mysql.com/doc/refman/5.5/en/sql-mode.html#sqlmode_allow_invalid_dates).

Do I have to enable a particular MySQL option?  For information, I'm using MySQL version 5.7.11

**Comment by bcivel** [comment]
Hello,
MySQL Database Version should be 5.6.
I add a try on 5.7 and I confirm the database script need to be adapted to be deployable on this version.
I update the documentation.
Thanks
Benoit

De : Aurélien Bourdon <notifications@github.com<mailto:notifications@github.com>>
Répondre à : vertigo17/Cerberus <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : vendredi 11 mars 2016 12:00
À : vertigo17/Cerberus <Cerberus@noreply.github.com<mailto:Cerberus@noreply.github.com>>
Objet : [Cerberus] Many errors during SQL table initialization (#684)


When I'm trying to initialize database for the first time, I've got many SQL errors:

[capture d ecran 2016-03-11 a 11 50 07]<https://cloud.githubusercontent.com/assets/1511715/13700222/e06f490e-e77f-11e5-9c4e-ae3488cdee25.png>

[capture d ecran 2016-03-11 a 11 50 48]<https://cloud.githubusercontent.com/assets/1511715/13700223/e4715fd8-e77f-11e5-97ad-f98a7f668d6c.png>

[capture d ecran 2016-03-11 a 11 59 35]<https://cloud.githubusercontent.com/assets/1511715/13700351/c7fc28fa-e780-11e5-9f84-300ca095068d.png>

(and so on...)

It may be due to the use of bad timestamp format for default value (0000-00-00 00:00:00) when invalid dates are not allowed (http://dev.mysql.com/doc/refman/5.5/en/sql-mode.html#sqlmode_allow_invalid_dates).

Do I have to enable a particular MySQL option? For information, I'm using MySQL version 5.7.11

-
Reply to this email directly or view it on GitHub<https://github.com/vertigo17/Cerberus/issues/684>.

Les informations contenues dans ce message ainsi que dans les pièces jointes sont strictement confidentielles et réservées à l'usage exclusif de ses destinataires. Si vous prenez connaissance de ce message sans en être le (la) destinataire, vous êtes prié(e) d'en aviser immédiatement l'émetteur et de le détruire sous toutes ses formes. Toute diffusion ou publication, totale ou partielle, est interdite sauf autorisation expresse de l'émetteur. Les meilleurs efforts sont faits pour maintenir cette transmission exempte de tout virus mais l'intégrité de ce message n'est pas assurée sur Internet : il a pu être altéré ou falsifié. Les points de vue ou avis émanent de son auteur et ne représentent pas nécessairement ceux de la Société. Son contenu ne peut engager la responsabilité de La Redoute et de ses filiales. This message and any attachments are strictly confidential and intended solely for the addressees. If you have received this message in error please delete it and notify the sender immediately. Any dissemination or disclosure, either whole or partial, is prohibited except formal approval of the sender. Best efforts are made in order to keep this message free of virus, but integrity of this message is not guaranteed through the Internet : it could have been altered or falsified. The views or opinions presented here are solely of the author and do not necessarily represent those of the Enterprise. Its content cannot bind La Redoute and its subsidiaries.

**Comment by abourdon** [comment]
It works! Thanks!

**Comment by abourdon** [comment]
I reopened this issue because it is not completely solved.

Indeed, although I use a 5.6 MySQL version (5.6.29 more exactly), I've got a lot of:
`java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp`
causing insertion error on database, especially when saving test case execution.

I found a workaround by telling MySQL to deal with '0 date value' thanks to the following parameter:
`zeroDateTimeBehavior = round`
This property can be defined from the Glassfish console as a JDBC connection pool property.

But the question is: are there no side effect to affect a '0 date value' to the minimal valid one? Nevertheless, it could be great to fix this bug. 

See the following SO for more information: http://stackoverflow.com/questions/782823/handling-datetime-values-0000-00-00-000000-in-jdbc

**Comment by bcivel** [comment]
I finally solved this replacing the default timestamp from 0000-00-00 00:00:00 to 1970-01-01 01:01:01, which is the lowest timestamp that I can insert in MySQL 5.6 and 5.7. 

I'll double check on mariadb but it is supposed to be the same because this Timestamp is in the allowed range ('1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999')
