### ISSUE TITLE
Slide action to test Mobile applications

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#705]
Is it possible to implement a new action that will simulate the "slide" action (left, right, up and down) for mobile applications (Android and iOS)?

**Comment by abourdon** [comment]
Hi Filipe,

Could you have a concrete use case about the need of this swipe action? Because implementation could change according to what we want to really do.

Regards,
Aurélien

**Comment by ffazendeiro** [comment]
Hi Aurélien,
For example for the Redoute App on the PLP page for the "slide" up and down throughout the articles:
![image](https://cloud.githubusercontent.com/assets/17747042/14814272/8846f17c-0b9d-11e6-86ef-55cd811fabca.png)


The "slide" left and right can be used for example on the first login page to go to the next page (using something like "right to left"):
![slide](https://cloud.githubusercontent.com/assets/17747042/14814761/99901bfa-0b9f-11e6-904f-bdd572d11356.png)

Let me know if you need more information.
Thanks.
Best Regards,
Filipe

**Comment by abourdon** [comment]
Hi Filipe,

The _swipe_ action is now available and let you swipe on screen. Look at the documentation for more details.

Regards,
Aurélien

**Comment by vertigo17** [comment]
Aurélien, please remove the SwipeAction.java from cerberus/crud/entity/
This package is dedicated to crud obects from database.
Create a package under org.cerberus.service.engine.entity

**Comment by abourdon** [comment]
Sure Benoit.

So I moved the `SwipeAction` class under the `org.cerberus.service.engine.model` package. This new package is dedicated to gather model classes used by the service engine process.
(Note that final package is named **model** and not **entity** because is more relevant. Indeed, classes under this package are not database entities but model classes)

I see there are other classes/packages that could be put under this new package:
- `org.cerberus.util.answer.Answer`
- `org.cerberus.util.answer.AnswerItem`
- `org.cerberus.util.answer.AnswerList`
- `org.cerberus.service.engine.impl.diff`
- `org.cerberus.service.engine.impl.input`
- ... maybe more

I'm going to create a new issue to move all of them
