### ISSUE TITLE
Error parsing xpath expressions on Test Data Lib

### ISSUE THREAD

**Issue by spinto-redoute-pt** [vertigo17/Cerberus#721]
Hi,

Parsing expression for SOAP requests in the test data lib is being encoded.
Using the expression: `//ColumnName[text() ='NUM_CLI']/../ColumnValue`
Raises the error: `The evaluation of the xpath expression '//ColumnName[text() &#61;&#39;NUM_CLI&#39;]/../ColumnValue' specified in the sub-data entry '' for the library entry '419' has failed! 'org.cerberus.util.XmlUtilException: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: Expected ], but found: &#61;&#39;NUM_CLI&#39;'
`

Can you please check this?

Regards
Sérgio Pinto

**Comment by vertigo17** [comment]
In fact the values in the database has some characters encoded that prevent the test to execute.
I created a SQL script to clean the values on the database.
I also commit a change to prevent the encoded characters to appear in order to fix the issue once for all. Please ask Guilherme to run the SQL against database to clean it and try again from QA or after new deploy in Prod.
Don't hesitate to reopen if after that it still doesn't work
