### ISSUE TITLE
No screenshot on error for Android application

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#729]
When a test fail for an Android application no image is recorded although the Screenshot option is set to 1 (Screenshot on error).

**Comment by MichaelWil** [comment]
Hi,
From what i can see now it seems that the issue is not completely solved. Based on the history i've been looking into i can say that 
1- tests which are FA have all screenshots
2- tests which are KO don't have all the time a screenshot. The same day i can see (for example) that http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32885245 have a screenshot while http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32886416 don't. 
This shows that the expected behaviour is eratic which is not correct.

Can you please re-open this bug and take a look, please ? Or maybe it's better opening a new issue ? 
Can you please advise ?

Thanks
