### ISSUE TITLE
Run TestCase improvements

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#753]
Hi,
it would be good to have two things in the rustestcase:
1 - The environment list having only the environments activated for the test being run
2 - Let's say i have a run like this one http://192.168.134.35/Cerberus/RunTests.jsp?Test=Recommended%20products&TestCase=0007C&MySystem=&Country=BE&Environment=PREVIEW&browser=firefox&Tag=WEB_THESEUS_ALL_UAT_2016032306 wich says the environment is Preview. If preview is disabled, cerberus should give a feedback informing that the Environment in wich i want to run the test is disabled.

Thanks!

**Comment by vertigo17** [comment]
Rui, we no longer support the old RunTest.jsp page.

http://192.168.134.35/Cerberus/RunTests1.jsp?test=Recommended%20products&testcase=0007C&MySystem=&country=BE&environment=PREVIEW&browser=firefox&tag=WEB_THESEUS_ALL_UAT_2016032306

On the new page RunTest1.jsp, we can select multiple testcases on different test so for 1/ this is not possible to display in the environment select box the status of the environment for that testcase.
Can you confirm that what you call 'environment activated for the test' is taking into acount the ActiveQA, ActiveUAT and ActivePROD data ? I ask the question because on your example all are active. 
If the actve you have in mind if the active of the environment itself (not the flag attached to the testcase), This is not relevant either to put it on the GUI as the execution maybe queued and when it will be executed, the environment maybe back up.
Still if we want to put the information at the time the page is open, it is at an environment + country level so 1 environment can be active for 1 country and inactive for another. Putting a rule to inform when all is possible and not a bad idea but please confirm it on the new screen with a quick mockup of what you expect.

**Comment by vertigo17** [comment]
I added on each environment where every countries are desactivated, a [currently disabled] information.
