### ISSUE TITLE
ISSUE Execution detail Copy / paste

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#778]
Hello,

I found out a bug when copying and pasting execution detail page.

The page is different when I send the URL.
You will find 2 screenshots with the same URL and differences in the execution detail

![execution](https://cloud.githubusercontent.com/assets/18569182/15498180/cfe4b7dc-219e-11e6-848c-9e385f03e66b.JPG)

![executionafterpasting](https://cloud.githubusercontent.com/assets/18569182/15498251/1ce4ac68-219f-11e6-9a11-b89022c8d13b.JPG)

Thank you

Cerberus Version : 1.1.4-SNAPSHOT

**Comment by vertigo17** [comment]
Nice issue that was an opportunity to spend several minutes playing the 7 mistake games of my childhood. Thanks for that ;-)
To enrich the issue here are the error I could find :
1/The description of the FA step 
2/The description of the Action
I suppose the snapshot do not cover the same area so the gap in property (there is 1 more prop in the 1st image) is a trap and not a real difference.

If this is the case, this is a known issue where descriptions of step and actions and even control are not copy from testcase to the execution.
In case you modify them, the corresponding executions gets the new value.
Confirmed as beeing a real thing to improve.
