### ISSUE TITLE
Test not fuly loaded in Cerberus QA

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#798]
Test are not fully loaded and cannot be executed in cerberus QA (http://192.168.134.197).
For example with "Run this Test Case" the test are not loaded and test cannot be executed. For system THESEUS test case "TAG Commander-0117B" cannot be executed because it is only loaded to test "Page list":
![image](https://cloud.githubusercontent.com/assets/17747042/15784794/0a406d62-29ac-11e6-9649-a026d59e5378.png)
With "Run Multiple Test" the test stays with status NE:
![image](https://cloud.githubusercontent.com/assets/17747042/15784685/7f579554-29ab-11e6-97f5-15e472a5f66a.png)
Could you please check if all is ok with the getTestCaseList.
Thanks.

**Comment by bcivel** [comment]
Related with #797.
Will be corrected asap adding a script to update tables set timestamp to the default value.
Now, it?s no more possible to insert zero value for timestamp.

Beno?t CIVEL
RHSE IT
Tel: +33 3 20 69 65 42
Mob: +33 6 29 75 58 15

Le 3 juin 2016 ? 17:58, "ffazendeiro" <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Test are not fully loaded and cannot be executed in cerberus QA (http://192.168.134.197).
For example with "Run this Test Case" the test are not loaded and test cannot be executed. For system THESEUS test case "TAG Commander-0117B" cannot be executed because it is only loaded to test "Page list":
[image]<https://cloud.githubusercontent.com/assets/17747042/15784794/0a406d62-29ac-11e6-9649-a026d59e5378.png>
With "Run Multiple Test" the test stays with status NE:
[image]<https://cloud.githubusercontent.com/assets/17747042/15784685/7f579554-29ab-11e6-97f5-15e472a5f66a.png>
Could you please check if all is ok with the getTestCaseList.
Thanks.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/vertigo17/Cerberus/issues/798>, or mute the thread<https://github.com/notifications/unsubscribe/AFIIuGP0kabk_MecoLrpNKnoF2EAwk6Gks5qIE83gaJpZM4Itq9q>.

Les informations contenues dans ce message ainsi que dans les pi?ces jointes sont strictement confidentielles et r?serv?es ? l'usage exclusif de ses destinataires. Si vous prenez connaissance de ce message sans en ?tre le (la) destinataire, vous ?tes pri?(e) d'en aviser imm?diatement l'?metteur et de le d?truire sous toutes ses formes. Toute diffusion ou publication, totale ou partielle, est interdite sauf autorisation expresse de l'?metteur. Les meilleurs efforts sont faits pour maintenir cette transmission exempte de tout virus mais l'int?grit? de ce message n'est pas assur?e sur Internet : il a pu ?tre alt?r? ou falsifi?. Les points de vue ou avis ?manent de son auteur et ne repr?sentent pas n?cessairement ceux de la Soci?t?. Son contenu ne peut engager la responsabilit? de La Redoute et de ses filiales. This message and any attachments are strictly confidential and intended solely for the addressees. If you have received this message in error please delete it and notify the sender immediately. Any dissemination or disclosure, either whole or partial, is prohibited except formal approval of the sender. Best efforts are made in order to keep this message free of virus, but integrity of this message is not guaranteed through the Internet : it could have been altered or falsified. The views or opinions presented here are solely of the author and do not necessarily represent those of the Enterprise. Its content cannot bind La Redoute and its subsidiaries.

**Comment by bcivel** [comment]
fixed with commit 2f37c8665a9e5ae34d3bcc7f8cb6724e8a9956bc
<img width="222" alt="capture d ecran 2016-06-03 a 20 20 49" src="https://cloud.githubusercontent.com/assets/5376184/15788636/c2d6a9ce-29c8-11e6-9267-437e34ed90a9.png">
