### ISSUE TITLE
Get multiple lines of data on getFromDataLib results

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#818]
When retrieving records using getFromDataLib is it possible to read any record from the SQL result or we can only read the first one? 

Thanks

**Comment by vertigo17** [comment]
It depend in the nature used on property definition inside the testcase.
If STATIC, only the 1st row will fetched
If RANDOM, RANDOMNEW or NOTINUSE, all records will the fetch and only one will be selected at the end (some are removed from the fetch when RANDOMNEW or NOTINUSE).
The nb of row fetch will be limited by the min of 
parameter : cerberus_testdatalib_fetchmax (that can be global or defined at the system level) - 100 is the default in case parameter is wrongly defined.
rowlimit (specified in property definition)

Please don't use RANDOMNEW or NOTINUSE until the last version of cerberus is installed (version 810 is necessary in order to use those 2 nature on our huge testexecution database).

What do you have in mind ?

**Comment by ruirpr** [comment]
Let's say i want to add 3 products to basket and the sql query gives me 10 products. If there's a way of reading the first one, then the second one, then the third one, i could use the same result to add all the products instead of using 3 properties/queries. Something like PRODUCT[1], PRODUCT[2], PRODUCT[3], product being the getfomdatalib property.
Thanks!

**Comment by vertigo17** [comment]
Good idea. I will put that in the backlog.

**Comment by vertigo17** [comment]
Syntax :
DATA(n)(SUBDATA)
Or
DATA.n.SUBDATA
With
DATA : name of the property defined in the testcase.
SUBDATA : name of the subdata
n : row nb starting at 1.

Ex:
PRODUCT.2.SIZE
Will retirn the size of the product of the 2nd row.

You can omit the row nb :
PRODUCT.SIZE
Will return the size of the product of the 1st row.

You can omit the subdata value.
PRODUCT.5
Will return the key value of the 5th row.

Nb of row to retreive needs to be defined in the length field of the property definition in the testcase.
A NA return code is generated when not enought record from the data source is available (either sql, soap, cvs or static)

**Comment by ruirpr** [comment]
Hi
we tried this but cant figure out how it works. Can you build a sample working test to demonstrate? 

Thanks!

**Comment by vertigo17** [comment]
We can share that next week (I will be in Portugal) but basicly You define a testdatalib in SQL where the result return more than 1 row.
Inside the testcase, you define a Property getFromDataLib the leugth value in testcase property will define the number of row retreived.
