### ISSUE TITLE
Pouvoir continuer le test malgré l'échec d'une Action

### ISSUE THREAD

**Issue by ageneauNOR** [vertigo17/Cerberus#819]
Cerberus Version : 1.1.4

J'aimerais avoir un champs pour pouvoir indiquer que le test continue même si une action échoue.

Si possible j'aimerais aussi pouvoir être informé dans les résultats sur les actions qui ont échouées.

**Comment by vertigo17** [comment]
In order to handle that, a new field has been created at the action level :
![image](https://cloud.githubusercontent.com/assets/5342048/16449574/9531f0f2-3df8-11e6-842f-b33e1f25444a.png)
If you leave the field empty, there will be no impact on the behaviour of the engine.
If we put PE, the execution will stay pending after the execution of the action no matter what is the result of the action.

In case the field is empty, it gives that :
![image](https://cloud.githubusercontent.com/assets/5342048/16449636/e4c31402-3df8-11e6-969b-e34b66d967cd.png)
The test stops and global exe status is FA.

In case the field is PE :
![image](https://cloud.githubusercontent.com/assets/5342048/16449661/079a5d78-3df9-11e6-8ec8-bd3676319fd3.png)
The test continue after the execution of the action. Status of the action is still FA but global execution Status is OK (could be KO or FA if another action/control is failing). Description of the action is also postfix with " -- Execution forced to continue."

Is that OK ?

**Comment by ageneauNOR** [comment]
Yes, I feel it should be good.

I'm just wondering about what the RC in Force RC stands for, do you mind explaining?

**Comment by vertigo17** [comment]
RC means Return code but in fact that new field do not change the return code of the action but more the status of the global execution.
I changed it on the screens to 
ForceExeStatus.
Change is ready and will be introduced in next release.

**Comment by ageneauNOR** [comment]
Alright Thank you
