### ISSUE TITLE
Display step, action & control numbers in natural order

### ISSUE THREAD

**Issue by abourdon** [vertigo17/Cerberus#825]
Due to #569, step, action & control numbers are now technicals and not recalculated every each save action. Hence, step, action & control numbers are not displayed in natural order. It could be great to re-have a natural order as before.

**Comment by vertigo17** [comment]
Purpose of the issue is to display sort everywhere instead of the technical ids in order to avoid confusions.
Tehnical keys should not be displayed anylonguer.
That clean needs to be done in :

- [ ] Detail execution page.
- [ ] TestCase page
- [ ] Manual execution page.

Displaying the target sort number during inserting the step/action is nice to have (considering that it will be OK as soon as page reloaded).
