### ISSUE TITLE
Actions/Controls with wrong number when adding or deleting

### ISSUE THREAD

**Issue by ffazendeiro** [vertigo17/Cerberus#828]
When adding or removing an action or control, the action/control number is not updated.
For example we added an action between 3 and 4 and the action number are not upadted after save:
![image](https://cloud.githubusercontent.com/assets/17747042/16377388/aa0b5d3e-3c5d-11e6-944b-628c2245ae30.png)
We have to update it manually.
Could be realated to issue #827

**Comment by vertigo17** [comment]
This is also related to #825 
The ids that are displayed so far are technical ids and once new rows are inserted this will be always a new number that will be created (in your example the technical id of the new line is 5 but order is correctly inserted between 3 and 4).
What can be improved to avoid your confusion is to hide the technical ids and only display the sort data.
This was done in order to secure that technical ids are never changed from the GUI fixing use step issue  #569.
