### ISSUE TITLE
Execution Detail / wrong execution timer on Action

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#830]
Cerberus Version : 1.1.5-SNAPSHOT

Hi,
Just ran an execution. An action (click something) I've been running 1000 of time already (yes yes) has behaved weired.
Usualy takes a few miliseconds.
This time, took more than 5 minutes.
My TimeOut was set to 300 Sec

See link below :
Step 4 : ADD 1st EO (Exposed Offer) to basket
Action 4 : ick Size Layer, depending old pdp or pdp "canapé"
As you see, action says 125ms to execute, while step says "359.219 s "
I insist, the action took actualy more than 300 sec

http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=33730415

regards,
PF

**Comment by abourdon** [comment]
Hi,

Step execution time is not only related to its action/control execution time but also its associated property computation time.

If you look at the `EO1_LAYER_SIZE_XPATH` property, you will see it requires 5'1'' to be computed. 
That's explain why the associated Step takes more than 359 seconds to be executed.

So this is not a bug. But I think it could be great to add the information about property time computation from each action or control to be more understandable.

I've just created this new issue in order to discuss about that: #846

Cheers,
Aurélien
