### ISSUE TITLE
Retry on different actions

### ISSUE THREAD

**Issue by pfoucray** [vertigo17/Cerberus#836]
Cerberus Version : 1.1.5-SNAPSHOT

Hi, in some cases, it would be usefull to be able to retry an action several time before considering it failed. Ex : SQL Request failing once, Twice, X time (depending TimeOut set)
Same behavior as Selenium retrying to find element before clicking it

regards,
PF

**Comment by vertigo17** [comment]
Please be more specific on the actions that could need a retry.
I don't see any SQL that needs retry to work.

**Comment by pfoucray** [comment]
Say you're doing some action in some application. This action writes a data in some DB but the time is not defined (unkown between 1 and 5 minuts)
You wanna try after 1 minut, then another min later if did not find, etc.

So far, you put several the same "control" et set it to "non fatal", but can't do the same for action (choosing if the result of 1st tries is critical or "ignorable")
--> I set Select count(*) from DB where blabla and then control integer = 1
--> I would set Select * from DB where blabla. Would be clearer, easier, faster :)

Regards,
Paul

**Comment by vertigo17** [comment]
For that you should perform the control after a wait action of 5 minutes or whatever you need (high enough so that the chance to succeed the control is acceptable).
If the global test still fail, the retry should be done at the level of the global execution (feature already exist to rerun when Exe Status <> OK) but not on a specific control.
In longer terms, we will implement condition on action execution that will allow to trigger an action after a given event.

**Comment by abourdon** [comment]
@vertigo17 so we forget this enhancement request?

**Comment by vertigo17** [comment]
Yes.

For me we can.
Les informations contenues dans ce message ainsi que dans les pièces jointes sont strictement confidentielles et réservées à l'usage exclusif de ses destinataires. Si vous prenez connaissance de ce message sans en être le (la) destinataire, vous êtes prié(e) d'en aviser immédiatement l'émetteur et de le détruire sous toutes ses formes. Toute diffusion ou publication, totale ou partielle, est interdite sauf autorisation expresse de l'émetteur. Les meilleurs efforts sont faits pour maintenir cette transmission exempte de tout virus mais l'intégrité de ce message n'est pas assurée sur Internet : il a pu être altéré ou falsifié. Les points de vue ou avis émanent de son auteur et ne représentent pas nécessairement ceux de la Société. Son contenu ne peut engager la responsabilité de La Redoute et de ses filiales. This message and any attachments are strictly confidential and intended solely for the addressees. If you have received this message in error please delete it and notify the sender immediately. Any dissemination or disclosure, either whole or partial, is prohibited except formal approval of the sender. Best efforts are made in order to keep this message free of virus, but integrity of this message is not guaranteed through the Internet : it could have been altered or falsified. The views or opinions presented here are solely of the author and do not necessarily represent those of the Enterprise. Its content cannot bind La Redoute and its subsidiaries.

**Comment by vertigo17** [comment]
I reopen the issue as beleive it could be a good idea for properties that result an NA.
For NOTINUSE, that could be handy to retry n times with a period of n miliseconds.
That would avoid to re execute completly the full test.
