### ISSUE TITLE
Would it be possible to implement some feature to manipulate strings for Android testcase

### ISSUE THREAD

**Issue by j0hnsa** [vertigo17/Cerberus#839]
Since we are not able to execute JS due to limitations in Appium would it be possible to implement some Properties like
String replace() or split()?

**Comment by bcivel** [comment]
Nice subject. 
Finally, limitation of android allow to identify functionnality we didn't implemented because we delegated to JS.

**Comment by abourdon** [comment]
Hi,

So what will be the needed property types?

Regards,
Aurélien

**Comment by vertigo17** [comment]
Or Control Types.
Scope of Properties should be reduced to test data as much as we can.
We should not force to create a property only because we need to manipulate data.

**Comment by abourdon** [comment]
We could consider several options, which can not only fit to this issue but enhance our core engine:

#### Add a new 'Eval' Property type

The 'Eval' Property type could take an expression that would be evaluated at runtime. Expression language would be dependent on the evaluation engine. For instance, in Groovy (because of its easily [Java integration](http://groovy-lang.org/integrating.html#integ-eval)) we could write something like this : 

`"foo bar".replace("bar", "baz")`

Then any `bar` words would be replaced by `baz` on the `foo bar` String (`foo baz` in our example).

An other interesting point, is that our _property interpretation mechanism_ could also be used, in order to produce more complex transformation between one or several properties. For instance:

`"%FOO%".replace("%BAR%", "%BAZ%")`

Then we could have the same powerful mechanism as our `executeJS` Property type, but now computed by our core engine instead of browser, and then compatible with any Application type, like Android one.

#### Add a new 'Transform' Property column

A new 'Transform' column could be added to the Property array to execute a transformation process after the Property value computation. This column could be split into several ones as the following: 

- a combo list of actions (replace, toUppercase, addToDate, ...)
- one or several columns acting as parameters for the selected transform action.

This approach would be more _functionally understandable_ and each action could be developed following the needs, as we can already do with Step's actions or controls.



Let me know,
Aurélien

**Comment by cjmachado** [comment]
> Add a new 'Eval' Property type

+1. Great idea, though I guess that all calculations would be performed on the server side. If it's true, then it might decrease overall performance.

**Comment by bcivel** [comment]
Both solution can be considered as they do not fit the exact same needs.

**Comment by abourdon** [comment]
So two new issues have been created to represent these two solutions.

And as development is done for #848 enhancement, we can close this issue
