### ISSUE TITLE
Found a OK with a FA

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#843]
This execution is OK with a FA in it: 
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=33832793

**Comment by vertigo17** [comment]
When there is an FA on CalculateProperty this could be normal that execution finish at OK. The real problem here is the PE on the property that never return the value.
Did you manage to reproduce it or it is a 1 shot error ?
If you can replicate, can you create a Cerberus regression test reproducing the crash on the XML Property ?

**Comment by ruirpr** [comment]
Duplicated the testcase and changed it in order to replicate the PE-FA-OK situation: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34047341

**Comment by vertigo17** [comment]
Last version of Cerberus generate a FA Execution.
I changed a bit the error message to be more clear.
In that execution, you put the xpath in the wrong field.
For getFromXml, Value1 should have the location of the XML (taks the last SOAP called if empty), Value2 should have the xpath.
