### ISSUE TITLE
Where should we write SQL Update ?

### ISSUE THREAD

**Issue by vitoo** [vertigo17/Cerberus#884]
Hello :)

We have tried executeSql and getFromDataLib_BETA and we got this error in both case :

`'java.sql.SQLException: Can not issue data manipulation statements with executeQuery().'.`

So how can we do an update statement ?

Thanks

**Comment by gmoita** [comment]
From my point of view, this should not be done as it can harm the database.

**Comment by vitoo** [comment]
What if there was a control dedicated to that action? This could limit the input tables to those that aren't compulsory.

**Comment by vertigo17** [comment]
The intent of executeSql and getFromDataLib_BETA **_properties_** is to get and manage test data (Properties). You should not use that to execute an SQL for which the purpose is not to get some test data.

I suppose if you want to perform an SQL that does an update or even run a store procedure, you need to use an **_action_**. It already exist 2 action for that need:
executeSqlUpdate  -->  To trigger any DELETE, UPDATE, INSERT SQL
executeSqlStoredProcedure  -->  To trigger any Store procedure.

**Comment by vitoo** [comment]
Oh, my bad, i was looking for this action in properties.

Thanks!

**Comment by vitoo** [comment]
And now we got a right problem :

> You cannot executeSqlUpdate using Cerberus connection pool. Please create new connection with dedicated rights.

Do you know where should we manage the rights ?

Thank you

**Comment by vertigo17** [comment]
As you can imagine, we do not allow to access to Cerberus database connecting using the Cerberus official connection Pool.
If you want to execute updates on Cerberus database (I hope you know what you are doing), you should create a new dedicated connection pool and name it differently (don't put cerberus in the name of the jdbc ressource).

**Comment by vitoo** [comment]
Yes, we are updating our own dataset. 

Actual error when trying to create our own pool : 

> Class name is wrong or classpath is not set for : com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource Please check the server.log for more details.

**Comment by vitoo** [comment]
Fixed by adding mysql-connector library to glassfish.

Now, when i execute the executeSqlUpdate, it stay pending and nothing is executed ...

**Comment by vertigo17** [comment]
What version do you use ? Please provide the application version as well as the database version number (from Admin / Database Maintenance).

On top of that, I guess from the screenshot that you use the executeSqlUpdate in order to get a randomaccount (probably not beeing used). If this is the case you can play with NATURE that can garantee it. Use it with getFromTestDataLib_BETA. RANDOM just pick a random value from the list, RANDOMNEW always pick a new from a list after each execution (until the build is changed) NOTINUSE garantee that no PE execution is already using the data (usefull for web accounts).

**Comment by vitoo** [comment]
version 1.1.5
Database : 833

Yes i want to mark a random account as used. 
The randomnew is working by testcase isnt it ?
On 2 different test case we may have the same account picked ?

> RANDOMNEW garantee that the same value will never be selected twice on the same test case, country, environment and build

**Comment by vertigo17** [comment]
Yes RANDOMNEW is working at testcase  country + environment + build level.
the aim of RANDOMNEW is to improve the test efficiency by picking always new values to test. That maximise the chance to find a bug ;-)
the aim of NOTINUSE is to manage the constrain that sometimes we have when we pick some data to test, we cannot use the same data. for ex : testing a basket of a website with 2 tests running in // on the same customer.  

Why do you mark the account for ? 
If this is to never us it again, use RANDOMNEW. (If you want different criteria we can discuss).
If this is to avoid picking it again during the execution of any test, use NOTINUSE.

I will try to reproduce your problem on executeUpdate as it should work (or report a clear error message in any case.)

**Comment by vitoo** [comment]
We want to randomize a new email like : compte1, compte2@gmail.com .... to create a new account with unused email. 

And i need to mark the account to know which account are created by automation, and maybe delete them in the future.


For my problem with executeUpdate, you have to know that when i created a new connection pool, it doesnt find the class used by cerberusprd, its weird, i had to add the mysql lib in GlassFish to make the connection pool pingable by GlassFish.

Thanks for your help

**Comment by vitoo** [comment]
Hi,

i've tried to do a new connection pool in last version. 

So in the glassfish log i got : 

Cerberus default pool : 

```
Doing Action : executeSqlUpdate with object : cerberusprd and property : update jdd_test set test = 'okay' where test ='truc']]
Result of the action : FA You cannot executeSqlUpdate using Cerberus connection pool. Please create new connection with dedicated rights.]]
```

New pool : 
```
Doing Action : executeSqlUpdate with object : testprd and property : update jdd_test set test = 'okay' where test ='truc']]
 Trying to retrieve parameter : cerberus_actionexecutesqlupdate_timeout - [DEFAULT]]]
```

And it stay pending, no timeout

**Comment by vertigo17** [comment]
I beleive you got a nullPointer exception due to the fact that database is not configured at environment level.
The action deserve a better management of the error and better documentation... I will fix that to make it easier to use and self explained when executed.

In fact, in the action definition, the object parameter should contain the database name that you want to send the SQL to (and not the connectionpool like specified in the documentation).
Then, on the corresponding environment you are executing the SQL, you should configure the same database with the connection pool you configured:

Ex at action level (executeSQL points to crb and property contains the SQL I want to perform):
![selection_136](https://cloud.githubusercontent.com/assets/5342048/17835544/e7f8b8aa-6771-11e6-8bf9-f7afdbdb45a0.jpg)

At property level:
![selection_138](https://cloud.githubusercontent.com/assets/5342048/17835559/de755698-6772-11e6-8e5e-f9b51c1146ec.jpg)


At Environment level (crb database points to cerberusprd conncetionpool):
![selection_139](https://cloud.githubusercontent.com/assets/5342048/17835569/0f9af0e8-6773-11e6-915b-1d8f916d4811.jpg)

Result on execution:
![selection_140](https://cloud.githubusercontent.com/assets/5342048/17835571/2b344ed0-6773-11e6-831d-d435a21f7584.jpg)

**Comment by vertigo17** [comment]
Putting a database and not a connection pool JDBC ressource allow to make the test execution indepedent from the environment.

**Comment by vertigo17** [comment]
Fix is made in order to better manage the error when configuration is not correct (no more PE execution due to nullPointerException) and I will update the documentation later so keep the issue open.
If you can confirm that with the right config it works, let's keep the issue open untill the documentation is uptodate.

**Comment by vitoo** [comment]
It worked, thanks :+1:
