### ISSUE TITLE
Need new feature to modify properties during execution

### ISSUE THREAD

**Issue by R-Loic** [vertigo17/Cerberus#901]
Hello,

I will explain my need with an example : 

![property](https://cloud.githubusercontent.com/assets/18569182/18054903/146aa930-6e06-11e6-8845-a80ffced21c9.JPG)

 In this screenshot the value/property MESSAGE has to be modified during the execution, but I can't modify it. So I had to create several properties like this : 

![properties](https://cloud.githubusercontent.com/assets/18569182/18054569/bbea15b2-6e04-11e6-9b00-b12955b4fcc5.JPG)

The values are the same except for the message read.

A new action like Setproperty would be a solution. 
Example : 
Step 1- Setproperty MESSAGE = S1_MESSAGE
Step 2- Setproperty MESSAGE = S2_MESSAGE
Step 3- Setproperty MESSAGE = P1_MESSAGE

Thanks
Cerberus Version : 1.1.5-SNAPSHOT

**Comment by abourdon** [comment]
Hi Loïc,

@bcivel @vertigo17 what about using the second argument of the `calculateProperty` action? If this argument is filled, then `calculateProperty` would use this value instead of reading initial value from the property table.
This argument could be filled by a static value (`3` for instance), or by a property name (`%FOO%` for instance) to get country-related value.

Let me know,
Aurélien

**Comment by abourdon** [comment]
We chosen to not use static value but property name. This way, we can differentiate if value2 is not defined or defined by empty value.

So the real use is:
- If value1 is defined but not value2, then value1 is calculated (past behaviour)
- if value1 and value2 are defined, then value1 property is feeded by the value2 property calculation result.
- both value1 and value2 are property names
