### ISSUE TITLE
property not correctly calculated for country

### ISSUE THREAD

**Issue by ruirpr** [vertigo17/Cerberus#909]
Hi, 
it seems that a test fails when finding a property not defined for the running country.
Examples: 
http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35909807
-DROP_CURRENCY is only defined for VI and test fails for IT

http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=35909778
-DRP_DOWN is only defined for CH and UK and test fails for VI but OK in the step failing for IT

Is this a bug or new behaviour?

**Comment by vertigo17** [comment]
It is the new behaviour.
What is strange is that on previous version the click action did not have the property feeded in order to prevent the action beeing executed if property is not defined. I wonder how it could work.
n order to solve that we have 2 solutions:
- After the migration, you change always to ifPropertyExist with DROP_CURRENCY and DRP_DOWN in the C. Val.
- Before the migration you add the Property information at the action level. After that we will probably have to clean the Property field from %DROP_CURRENCY% or %DRP_DOWN% data (that can be done in a massive way on all actions that do not require 2 parameter).
I think option 2 is easier as it can be anticipated before the migration. Can you test that 1/ is solving the execution and that 2/ on today prod is not hurting the execution ?

**Comment by ruirpr** [comment]
Hi, 
it's clear we have to change allways to ifPropertyExists, didn't realised that earlier. Wouldn't it be easier to impot as 'ifPropertyExists' instead of 'allways'? 

I'm not fully understanding solution 2.
